services:
  image-reencoder:
    build: .
    ports:
    - "8080:8080"

    environment:
      - OUTPUT_MOUNT_PATH=/home/output_videos
      - REENCODE_CODEC=VP9
      - CRF_RANGE=75

    volumes:
      - ./container_output:/home/output_videos